// Generated by gencpp from file levy_cs69_a2/FindSignalStrengthResponse.msg
// DO NOT EDIT!


#ifndef LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTHRESPONSE_H
#define LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace levy_cs69_a2
{
template <class ContainerAllocator>
struct FindSignalStrengthResponse_
{
  typedef FindSignalStrengthResponse_<ContainerAllocator> Type;

  FindSignalStrengthResponse_()
    : avg_str(0.0)  {
    }
  FindSignalStrengthResponse_(const ContainerAllocator& _alloc)
    : avg_str(0.0)  {
  (void)_alloc;
    }



   typedef float _avg_str_type;
  _avg_str_type avg_str;





  typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindSignalStrengthResponse_

typedef ::levy_cs69_a2::FindSignalStrengthResponse_<std::allocator<void> > FindSignalStrengthResponse;

typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthResponse > FindSignalStrengthResponsePtr;
typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthResponse const> FindSignalStrengthResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace levy_cs69_a2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'levy_cs69_a2': ['/home/oliverlevyorl/CS69/catkin_ws/src/levy_cs69_a2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31fcbdc1bed5689fa5a0dc9cac81c933";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31fcbdc1bed5689fULL;
  static const uint64_t static_value2 = 0xa5a0dc9cac81c933ULL;
};

template<class ContainerAllocator>
struct DataType< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "levy_cs69_a2/FindSignalStrengthResponse";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 avg_str\n\
\n\
";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.avg_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindSignalStrengthResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::levy_cs69_a2::FindSignalStrengthResponse_<ContainerAllocator>& v)
  {
    s << indent << "avg_str: ";
    Printer<float>::stream(s, indent + "  ", v.avg_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTHRESPONSE_H
