// Generated by gencpp from file levy_cs69_a2/FindSignalStrength.msg
// DO NOT EDIT!


#ifndef LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTH_H
#define LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTH_H

#include <ros/service_traits.h>


#include <levy_cs69_a2/FindSignalStrengthRequest.h>
#include <levy_cs69_a2/FindSignalStrengthResponse.h>


namespace levy_cs69_a2
{

struct FindSignalStrength
{

typedef FindSignalStrengthRequest Request;
typedef FindSignalStrengthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindSignalStrength
} // namespace levy_cs69_a2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::levy_cs69_a2::FindSignalStrength > {
  static const char* value()
  {
    return "ab39b3c90f03c54cfc232becf20d8a15";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrength&) { return value(); }
};

template<>
struct DataType< ::levy_cs69_a2::FindSignalStrength > {
  static const char* value()
  {
    return "levy_cs69_a2/FindSignalStrength";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrength&) { return value(); }
};


// service_traits::MD5Sum< ::levy_cs69_a2::FindSignalStrengthRequest> should match 
// service_traits::MD5Sum< ::levy_cs69_a2::FindSignalStrength > 
template<>
struct MD5Sum< ::levy_cs69_a2::FindSignalStrengthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::levy_cs69_a2::FindSignalStrength >::value();
  }
  static const char* value(const ::levy_cs69_a2::FindSignalStrengthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::levy_cs69_a2::FindSignalStrengthRequest> should match 
// service_traits::DataType< ::levy_cs69_a2::FindSignalStrength > 
template<>
struct DataType< ::levy_cs69_a2::FindSignalStrengthRequest>
{
  static const char* value()
  {
    return DataType< ::levy_cs69_a2::FindSignalStrength >::value();
  }
  static const char* value(const ::levy_cs69_a2::FindSignalStrengthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::levy_cs69_a2::FindSignalStrengthResponse> should match 
// service_traits::MD5Sum< ::levy_cs69_a2::FindSignalStrength > 
template<>
struct MD5Sum< ::levy_cs69_a2::FindSignalStrengthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::levy_cs69_a2::FindSignalStrength >::value();
  }
  static const char* value(const ::levy_cs69_a2::FindSignalStrengthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::levy_cs69_a2::FindSignalStrengthResponse> should match 
// service_traits::DataType< ::levy_cs69_a2::FindSignalStrength > 
template<>
struct DataType< ::levy_cs69_a2::FindSignalStrengthResponse>
{
  static const char* value()
  {
    return DataType< ::levy_cs69_a2::FindSignalStrength >::value();
  }
  static const char* value(const ::levy_cs69_a2::FindSignalStrengthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTH_H
