// Generated by gencpp from file levy_cs69_a2/FindSignalStrengthRequest.msg
// DO NOT EDIT!


#ifndef LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTHREQUEST_H
#define LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace levy_cs69_a2
{
template <class ContainerAllocator>
struct FindSignalStrengthRequest_
{
  typedef FindSignalStrengthRequest_<ContainerAllocator> Type;

  FindSignalStrengthRequest_()
    : x(0)
    , y(0)
    , theta(0.0)  {
    }
  FindSignalStrengthRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindSignalStrengthRequest_

typedef ::levy_cs69_a2::FindSignalStrengthRequest_<std::allocator<void> > FindSignalStrengthRequest;

typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthRequest > FindSignalStrengthRequestPtr;
typedef boost::shared_ptr< ::levy_cs69_a2::FindSignalStrengthRequest const> FindSignalStrengthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace levy_cs69_a2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'levy_cs69_a2': ['/home/oliverlevyorl/CS69/catkin_ws/src/levy_cs69_a2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bbb9d09174792dc6528bb56a3b8cac1";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bbb9d09174792dcULL;
  static const uint64_t static_value2 = 0x6528bb56a3b8cac1ULL;
};

template<class ContainerAllocator>
struct DataType< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "levy_cs69_a2/FindSignalStrengthRequest";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
float32 theta\n\
";
  }

  static const char* value(const ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindSignalStrengthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::levy_cs69_a2::FindSignalStrengthRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEVY_CS69_A2_MESSAGE_FINDSIGNALSTRENGTHREQUEST_H
